2025-08-07 07:35:35 GMT [22]: [3-1] user=,db=,app=,client= LOG:  starting PostgreSQL 17.5 (Debian 17.5-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2025-08-07 07:35:35 GMT [22]: [4-1] user=,db=,app=,client= LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-08-07 07:35:35 GMT [22]: [5-1] user=,db=,app=,client= LOG:  listening on IPv6 address "::", port 5432
2025-08-07 07:35:35 GMT [22]: [6-1] user=,db=,app=,client= LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-08-07 07:35:35 GMT [27]: [1-1] user=,db=,app=,client= LOG:  database system was shut down at 2025-08-07 07:35:34 GMT
2025-08-07 07:35:35 GMT [22]: [7-1] user=,db=,app=,client= LOG:  database system is ready to accept connections
2025-08-07 07:35:45 GMT [33]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 07:35:45 GMT [33]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 07:35:45 GMT [33]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-07 07:35:45 GMT [33]: [4-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.013 user=postgres database=postgres host=[local]
2025-08-07 07:35:45 GMT [35]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 07:35:45 GMT [35]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 07:35:45 GMT [35]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-07 07:35:45 GMT [35]: [4-1] user=postgres,db=postgres,app=psql,client=[local] ERROR:  database "testdb" does not exist
2025-08-07 07:35:45 GMT [35]: [5-1] user=postgres,db=postgres,app=psql,client=[local] STATEMENT:  CREATE USER efm WITH LOGIN PASSWORD 'efm'; GRANT ALL PRIVILEGES ON DATABASE testdb TO efm;
2025-08-07 07:35:45 GMT [35]: [6-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.003 user=postgres database=postgres host=[local]
2025-08-07 07:36:04 GMT [49]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 07:36:04 GMT [49]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 07:36:04 GMT [49]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 07:36:04 GMT [49]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-07 07:36:20 GMT [50]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=33356
2025-08-07 07:36:20 GMT [50]: [2-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="replicator" method=md5 (/var/lib/postgresql/data/pg_hba.conf:18)
2025-08-07 07:36:20 GMT [50]: [3-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  replication connection authorized: user=replicator application_name=pg_basebackup
2025-08-07 07:36:20 GMT [25]: [1-1] user=,db=,app=,client= LOG:  checkpoint starting: force wait
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:36:20 GMT [30]: [1-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:36:20 GMT [30]: [2-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 07:36:20 GMT [25]: [2-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 7 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.410 s, sync=0.010 s, total=0.429 s; sync files=6, longest=0.003 s, average=0.002 s; distance=11374 kB, estimate=11374 kB; lsn=0/20000B8, redo lsn=0/2000028
2025-08-07 07:36:20 GMT [53]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=33368
2025-08-07 07:36:20 GMT [53]: [2-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="replicator" method=md5 (/var/lib/postgresql/data/pg_hba.conf:18)
2025-08-07 07:36:20 GMT [53]: [3-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  replication connection authorized: user=replicator application_name=pg_basebackup
2025-08-07 07:36:20 GMT [50]: [4-1] user=replicator,db=[unknown],app=pg_basebackup,client=172.20.0.11 LOG:  temporary file: path "base/pgsql_tmp/pgsql_tmp50.0", size 137509
2025-08-07 07:36:20 GMT [50]: [5-1] user=replicator,db=[unknown],app=pg_basebackup,client=172.20.0.11 STATEMENT:  BASE_BACKUP ( LABEL 'pg_basebackup base backup',  PROGRESS,  WAIT 0,  MANIFEST 'yes',  TARGET 'client')
2025-08-07 07:36:20 GMT [50]: [6-1] user=replicator,db=[unknown],app=pg_basebackup,client=172.20.0.11 LOG:  disconnection: session time: 0:00:00.537 user=replicator database= host=172.20.0.11 port=33356
2025-08-07 07:36:20 GMT [53]: [4-1] user=replicator,db=[unknown],app=pg_basebackup,client=172.20.0.11 LOG:  disconnection: session time: 0:00:00.071 user=replicator database= host=172.20.0.11 port=33368
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:36:21 GMT [30]: [3-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:36:21 GMT [30]: [4-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:36:22 GMT [30]: [5-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:36:22 GMT [30]: [6-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 07:36:22 GMT [30]: [7-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:36:22 GMT [30]: [8-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:36:22 GMT [30]: [9-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:36:23 GMT [30]: [10-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:36:23 GMT [30]: [11-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:36:24 GMT [30]: [12-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:36:24 GMT [30]: [13-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 07:36:24 GMT [30]: [14-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
2025-08-07 07:36:34 GMT [71]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 07:36:34 GMT [71]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 07:36:34 GMT [71]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 07:36:34 GMT [71]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-07 07:37:04 GMT [80]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 07:37:04 GMT [80]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 07:37:04 GMT [80]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 07:37:04 GMT [80]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:37:24 GMT [30]: [15-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:37:24 GMT [30]: [16-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:37:25 GMT [30]: [17-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:37:25 GMT [30]: [18-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:37:26 GMT [30]: [19-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:37:26 GMT [30]: [20-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 07:37:26 GMT [30]: [21-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
2025-08-07 07:37:34 GMT [95]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 07:37:34 GMT [95]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 07:37:34 GMT [95]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 07:37:34 GMT [95]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-07 07:37:35 GMT [96]: [1-1] user=,db=,app=,client= LOG:  automatic analyze of table "template1.pg_catalog.pg_type"
	I/O timings: read: 3.912 ms, write: 0.035 ms
	avg read rate: 17.127 MB/s, avg write rate: 2.704 MB/s
	buffer usage: 1021 hits, 57 misses, 9 dirtied
	system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.02 s
2025-08-07 07:37:35 GMT [96]: [2-1] user=,db=,app=,client= LOG:  automatic analyze of table "template1.pg_catalog.pg_attribute"
	I/O timings: read: 0.324 ms, write: 0.006 ms
	avg read rate: 17.756 MB/s, avg write rate: 4.261 MB/s
	buffer usage: 483 hits, 25 misses, 6 dirtied
	system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.01 s
2025-08-07 07:37:35 GMT [96]: [3-1] user=,db=,app=,client= LOG:  automatic aggressive vacuum of table "template1.pg_catalog.pg_class": index scans: 0
	pages: 0 removed, 14 remain, 14 scanned (100.00% of total)
	tuples: 0 removed, 415 remain, 0 are dead but not yet removable
	removable cutoff: 742, which was 0 XIDs old when operation ended
	new relfrozenxid: 742, which is 12 XIDs ahead of previous value
	frozen: 0 pages from table (0.00% of total) had 0 tuples frozen
	index scan not needed: 0 pages from table (0.00% of total) had 0 dead item identifiers removed
	I/O timings: read: 0.135 ms, write: 0.000 ms
	avg read rate: 176.222 MB/s, avg write rate: 29.370 MB/s
	buffer usage: 51 hits, 6 misses, 1 dirtied
	WAL usage: 1 records, 1 full page images, 2641 bytes
	system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-08-07 07:37:35 GMT [96]: [4-1] user=,db=,app=,client= LOG:  automatic analyze of table "template1.pg_catalog.pg_class"
	I/O timings: read: 0.036 ms, write: 0.006 ms
	avg read rate: 7.812 MB/s, avg write rate: 6.510 MB/s
	buffer usage: 528 hits, 6 misses, 5 dirtied
	system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-08-07 07:37:35 GMT [96]: [5-1] user=,db=,app=,client= LOG:  automatic analyze of table "template1.pg_catalog.pg_constraint"
	I/O timings: read: 0.088 ms, write: 0.023 ms
	avg read rate: 9.115 MB/s, avg write rate: 6.510 MB/s
	buffer usage: 526 hits, 7 misses, 5 dirtied
	system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-08-07 07:37:35 GMT [96]: [6-1] user=,db=,app=,client= LOG:  automatic analyze of table "template1.pg_catalog.pg_rewrite"
	I/O timings: read: 0.227 ms, write: 0.006 ms
	avg read rate: 125.000 MB/s, avg write rate: 15.625 MB/s
	buffer usage: 116 hits, 16 misses, 2 dirtied
	system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-08-07 07:37:35 GMT [96]: [7-1] user=,db=,app=,client= LOG:  automatic analyze of table "template1.pg_catalog.pg_description"
	I/O timings: read: 0.605 ms, write: 0.000 ms
	avg read rate: 75.000 MB/s, avg write rate: 4.688 MB/s
	buffer usage: 74 hits, 48 misses, 3 dirtied
	system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-08-07 07:37:35 GMT [96]: [8-1] user=,db=,app=,client= LOG:  automatic aggressive vacuum of table "template1.pg_catalog.pg_depend": index scans: 0
	pages: 0 removed, 13 remain, 13 scanned (100.00% of total)
	tuples: 0 removed, 1709 remain, 0 are dead but not yet removable
	removable cutoff: 746, which was 0 XIDs old when operation ended
	new relfrozenxid: 746, which is 16 XIDs ahead of previous value
	frozen: 0 pages from table (0.00% of total) had 0 tuples frozen
	index scan not needed: 0 pages from table (0.00% of total) had 0 dead item identifiers removed
	I/O timings: read: 0.396 ms, write: 0.000 ms
	avg read rate: 235.990 MB/s, avg write rate: 12.421 MB/s
	buffer usage: 54 hits, 19 misses, 1 dirtied
	WAL usage: 1 records, 1 full page images, 7869 bytes
	system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-08-07 07:37:35 GMT [96]: [9-1] user=,db=,app=,client= LOG:  automatic analyze of table "template1.pg_catalog.pg_depend"
	I/O timings: read: 0.000 ms, write: 0.007 ms
	avg read rate: 0.000 MB/s, avg write rate: 7.812 MB/s
	buffer usage: 109 hits, 0 misses, 2 dirtied
	system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-08-07 07:37:35 GMT [96]: [10-1] user=,db=,app=,client= LOG:  automatic analyze of table "template1.pg_catalog.pg_ts_config_map"
	I/O timings: read: 0.102 ms, write: 0.000 ms
	avg read rate: 39.062 MB/s, avg write rate: 7.812 MB/s
	buffer usage: 56 hits, 5 misses, 1 dirtied
	system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-08-07 07:37:35 GMT [96]: [11-1] user=,db=,app=,client= LOG:  automatic analyze of table "template1.pg_catalog.pg_init_privs"
	I/O timings: read: 0.097 ms, write: 0.000 ms
	avg read rate: 39.062 MB/s, avg write rate: 7.812 MB/s
	buffer usage: 84 hits, 5 misses, 1 dirtied
	system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-08-07 07:37:35 GMT [96]: [12-1] user=,db=,app=,client= LOG:  automatic analyze of table "template1.pg_catalog.pg_collation"
	I/O timings: read: 0.131 ms, write: 0.000 ms
	avg read rate: 62.500 MB/s, avg write rate: 3.906 MB/s
	buffer usage: 133 hits, 16 misses, 1 dirtied
	system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-08-07 07:37:35 GMT [96]: [13-1] user=,db=,app=,client= LOG:  automatic analyze of table "template1.information_schema.sql_features"
	I/O timings: read: 0.117 ms, write: 0.007 ms
	avg read rate: 50.781 MB/s, avg write rate: 15.625 MB/s
	buffer usage: 175 hits, 13 misses, 4 dirtied
	system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-08-07 07:37:37 GMT [115]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 07:37:37 GMT [115]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 07:37:37 GMT [115]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-07 07:37:37 GMT [115]: [4-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.004 user=postgres database=postgres host=[local]
2025-08-07 07:37:37 GMT [122]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=::1 LOG:  connection received: host=::1 port=51872
2025-08-07 07:37:37 GMT [129]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 07:37:37 GMT [129]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 07:37:37 GMT [129]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-07 07:37:37 GMT [129]: [4-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-07 07:37:38 GMT [136]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 07:37:38 GMT [136]: [2-1] user=postgres,db=testdb,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 07:37:38 GMT [136]: [3-1] user=postgres,db=testdb,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=testdb application_name=psql
2025-08-07 07:37:38 GMT [136]: [4-1] user=postgres,db=testdb,app=[unknown],client=[local] FATAL:  database "testdb" does not exist
2025-08-07 07:38:04 GMT [145]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 07:38:04 GMT [145]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 07:38:04 GMT [145]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 07:38:04 GMT [145]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.004 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:38:26 GMT [30]: [22-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:38:26 GMT [30]: [23-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:38:27 GMT [30]: [24-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:38:27 GMT [30]: [25-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:38:28 GMT [30]: [26-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:38:28 GMT [30]: [27-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 07:38:28 GMT [30]: [28-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
2025-08-07 07:38:35 GMT [160]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 07:38:35 GMT [160]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 07:38:35 GMT [160]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 07:38:35 GMT [160]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-07 07:38:35 GMT [161]: [1-1] user=,db=,app=,client= LOG:  automatic aggressive vacuum of table "template1.pg_catalog.pg_statistic": index scans: 1
	pages: 0 removed, 26 remain, 26 scanned (100.00% of total)
	tuples: 125 removed, 410 remain, 0 are dead but not yet removable
	removable cutoff: 751, which was 0 XIDs old when operation ended
	new relfrozenxid: 751, which is 21 XIDs ahead of previous value
	frozen: 15 pages from table (57.69% of total) had 164 tuples frozen
	index scan needed: 15 pages from table (57.69% of total) had 145 dead item identifiers removed
	index "pg_statistic_relid_att_inh_index": pages: 5 in total, 0 newly deleted, 0 currently deleted, 0 reusable
	I/O timings: read: 1.585 ms, write: 0.000 ms
	avg read rate: 7.505 MB/s, avg write rate: 3.752 MB/s
	buffer usage: 95 hits, 4 misses, 2 dirtied
	WAL usage: 64 records, 3 full page images, 22113 bytes
	system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-08-07 07:39:05 GMT [169]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 07:39:05 GMT [169]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 07:39:05 GMT [169]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 07:39:05 GMT [169]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:39:28 GMT [30]: [29-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:39:28 GMT [30]: [30-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:39:29 GMT [30]: [31-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:39:29 GMT [30]: [32-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
cp: cannot create regular file '/var/lib/postgresql/archive/000000010000000000000001': No such file or directory
2025-08-07 07:39:30 GMT [30]: [33-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-07 07:39:30 GMT [30]: [34-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/000000010000000000000001 && cp pg_wal/000000010000000000000001 /var/lib/postgresql/archive/000000010000000000000001
2025-08-07 07:39:30 GMT [30]: [35-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "000000010000000000000001" failed too many times, will try again later
2025-08-07 07:39:35 GMT [184]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 07:39:35 GMT [184]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 07:39:35 GMT [184]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 07:39:35 GMT [184]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-07 07:40:05 GMT [193]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-07 07:40:05 GMT [193]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-07 07:40:05 GMT [193]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-07 07:40:05 GMT [193]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.005 user=postgres database=postgres host=[local]
