2025-08-08 02:32:02 GMT [1167]: [3-1] user=,db=,app=,client= LOG:  starting PostgreSQL 17.5 (Debian 17.5-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2025-08-08 02:32:02 GMT [1167]: [4-1] user=,db=,app=,client= LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-08-08 02:32:02 GMT [1167]: [5-1] user=,db=,app=,client= LOG:  listening on IPv6 address "::", port 5432
2025-08-08 02:32:02 GMT [1167]: [6-1] user=,db=,app=,client= LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-08-08 02:32:02 GMT [1171]: [1-1] user=,db=,app=,client= LOG:  database system was shut down at 2025-08-08 02:31:59 GMT
2025-08-08 02:32:02 GMT [1171]: [2-1] user=,db=,app=,client= LOG:  entering standby mode
2025-08-08 02:32:02 GMT [1171]: [3-1] user=,db=,app=,client= LOG:  consistent recovery state reached at 0/90000A0
2025-08-08 02:32:02 GMT [1171]: [4-1] user=,db=,app=,client= LOG:  invalid record length at 0/90000A0: expected at least 24, got 0
2025-08-08 02:32:02 GMT [1167]: [7-1] user=,db=,app=,client= LOG:  database system is ready to accept read-only connections
2025-08-08 02:32:02 GMT [1172]: [1-1] user=,db=,app=,client= LOG:  fetching timeline history file for timeline 6 from primary server
2025-08-08 02:32:02 GMT [1172]: [2-1] user=,db=,app=,client= LOG:  started streaming WAL from primary at 0/9000000 on timeline 5
2025-08-08 02:32:02 GMT [1172]: [3-1] user=,db=,app=,client= LOG:  replication terminated by primary server
2025-08-08 02:32:02 GMT [1172]: [4-1] user=,db=,app=,client= DETAIL:  End of WAL reached on timeline 5 at 0/90000A0.
2025-08-08 02:32:02 GMT [1172]: [5-1] user=,db=,app=,client= FATAL:  terminating walreceiver process due to administrator command
2025-08-08 02:32:02 GMT [1171]: [5-1] user=,db=,app=,client= LOG:  new target timeline is 6
2025-08-08 02:32:02 GMT [1173]: [1-1] user=,db=,app=,client= LOG:  started streaming WAL from primary at 0/9000000 on timeline 6
2025-08-08 02:32:02 GMT [1171]: [6-1] user=,db=,app=,client= LOG:  redo starts at 0/90000A0
2025-08-08 02:32:02 GMT [1174]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=45262
2025-08-08 02:32:02 GMT [1174]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:32:02 GMT [1174]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:32:02 GMT [1174]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.005 user=efm database=postgres host=172.20.0.10 port=45262
2025-08-08 02:32:02 GMT [1185]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=45276
2025-08-08 02:32:02 GMT [1186]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=45292
2025-08-08 02:32:02 GMT [1185]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:32:02 GMT [1185]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:32:02 GMT [1187]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=48628
2025-08-08 02:32:02 GMT [1186]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:32:02 GMT [1186]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:32:02 GMT [1185]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.002 user=efm database=postgres host=172.20.0.10 port=45276
2025-08-08 02:32:02 GMT [1186]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.002 user=efm database=postgres host=172.20.0.10 port=45292
2025-08-08 02:32:02 GMT [1187]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:32:02 GMT [1187]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:32:02 GMT [1188]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.12 LOG:  connection received: host=172.20.0.12 port=57758
2025-08-08 02:32:02 GMT [1187]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.11 LOG:  disconnection: session time: 0:00:00.003 user=efm database=postgres host=172.20.0.11 port=48628
2025-08-08 02:32:02 GMT [1192]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=45298
2025-08-08 02:32:02 GMT [1188]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.12 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:32:02 GMT [1188]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.12 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:32:02 GMT [1192]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:32:02 GMT [1192]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:32:02 GMT [1188]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.12 LOG:  disconnection: session time: 0:00:00.006 user=efm database=postgres host=172.20.0.12 port=57758
2025-08-08 02:32:03 GMT [1296]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=45308
2025-08-08 02:32:03 GMT [1296]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:32:03 GMT [1296]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:32:03 GMT [1296]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.036 user=efm database=postgres host=172.20.0.10 port=45308
2025-08-08 02:32:03 GMT [1298]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=45322
2025-08-08 02:32:03 GMT [1298]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:32:03 GMT [1298]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:32:03 GMT [1298]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.003 user=efm database=postgres host=172.20.0.10 port=45322
2025-08-08 02:32:03 GMT [1299]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=45336
2025-08-08 02:32:03 GMT [1299]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:32:03 GMT [1299]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:32:03 GMT [1299]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.002 user=efm database=postgres host=172.20.0.10 port=45336
2025-08-08 02:32:18 GMT [1309]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:32:18 GMT [1309]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:32:18 GMT [1309]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:32:18 GMT [1309]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:32:36 GMT [1311]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:32:36 GMT [1311]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:32:36 GMT [1311]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-08 02:32:41 GMT [1311]: [4-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:04.574 user=postgres database=postgres host=[local]
2025-08-08 02:32:48 GMT [1319]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:32:48 GMT [1319]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:32:48 GMT [1319]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:32:48 GMT [1319]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-08 02:33:04 GMT [1419]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=59024
2025-08-08 02:33:04 GMT [1419]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:33:04 GMT [1419]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:33:04 GMT [1419]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.026 user=efm database=postgres host=172.20.0.10 port=59024
2025-08-08 02:33:04 GMT [1424]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=50686
2025-08-08 02:33:04 GMT [1424]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:33:04 GMT [1424]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:33:04 GMT [1424]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.11 LOG:  disconnection: session time: 0:00:00.002 user=efm database=postgres host=172.20.0.11 port=50686
2025-08-08 02:33:04 GMT [1173]: [2-1] user=,db=,app=,client= LOG:  replication terminated by primary server
2025-08-08 02:33:04 GMT [1173]: [3-1] user=,db=,app=,client= DETAIL:  End of WAL reached on timeline 6 at 0/A0000A0.
2025-08-08 02:33:04 GMT [1173]: [4-1] user=,db=,app=,client= FATAL:  could not send end-of-streaming message to primary: server closed the connection unexpectedly
		This probably means the server terminated abnormally
		before or while processing the request.
	no COPY in progress
2025-08-08 02:33:04 GMT [1171]: [7-1] user=,db=,app=,client= LOG:  invalid record length at 0/A0000A0: expected at least 24, got 0
2025-08-08 02:33:04 GMT [1425]: [1-1] user=,db=,app=,client= FATAL:  could not connect to the primary server: connection to server at "172.20.0.11", port 5432 failed: FATAL:  the database system is shutting down
2025-08-08 02:33:04 GMT [1171]: [8-1] user=,db=,app=,client= LOG:  waiting for WAL to become available at 0/A0000B8
2025-08-08 02:33:07 GMT [1171]: [9-1] user=,db=,app=,client= LOG:  received promote request
2025-08-08 02:33:07 GMT [1171]: [10-1] user=,db=,app=,client= LOG:  redo done at 0/A000028 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 64.79 s
2025-08-08 02:33:07 GMT [1171]: [11-1] user=,db=,app=,client= LOG:  selected new timeline ID: 7
2025-08-08 02:33:07 GMT [1192]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 ERROR:  standby promotion is ongoing
2025-08-08 02:33:07 GMT [1192]: [5-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 HINT:  pg_wal_replay_resume() cannot be executed after promotion is triggered.
2025-08-08 02:33:07 GMT [1192]: [6-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 STATEMENT:  select pg_wal_replay_resume()
2025-08-08 02:33:07 GMT [1171]: [12-1] user=,db=,app=,client= LOG:  archive recovery complete
2025-08-08 02:33:07 GMT [1169]: [1-1] user=,db=,app=,client= LOG:  checkpoint starting: force
2025-08-08 02:33:07 GMT [1167]: [8-1] user=,db=,app=,client= LOG:  database system is ready to accept connections
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:33:07 GMT [1452]: [1-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:33:07 GMT [1452]: [2-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:33:07 GMT [1456]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=39084
2025-08-08 02:33:07 GMT [1456]: [2-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="replicator" method=md5 (/var/lib/postgresql/data/pg_hba.conf:18)
2025-08-08 02:33:07 GMT [1456]: [3-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  replication connection authorized: user=replicator application_name=efm_cluster_standby
2025-08-08 02:33:07 GMT [1456]: [4-1] user=replicator,db=[unknown],app=efm_cluster_standby,client=172.20.0.11 LOG:  disconnection: session time: 0:00:00.006 user=replicator database= host=172.20.0.11 port=39084
2025-08-08 02:33:07 GMT [1457]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=39086
2025-08-08 02:33:07 GMT [1457]: [2-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="replicator" method=md5 (/var/lib/postgresql/data/pg_hba.conf:18)
2025-08-08 02:33:07 GMT [1457]: [3-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  replication connection authorized: user=replicator application_name=efm_cluster_standby
2025-08-08 02:33:07 GMT [1169]: [2-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 2 recycled; write=0.102 s, sync=0.006 s, total=0.128 s; sync files=3, longest=0.003 s, average=0.002 s; distance=16384 kB, estimate=16384 kB; lsn=0/A000168, redo lsn=0/A0000D8
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:33:08 GMT [1452]: [3-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:33:08 GMT [1452]: [4-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:33:09 GMT [1452]: [5-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:33:09 GMT [1452]: [6-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:33:09 GMT [1452]: [7-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:33:14 GMT [1565]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=57272
2025-08-08 02:33:14 GMT [1565]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:33:14 GMT [1565]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:33:14 GMT [1565]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.034 user=efm database=postgres host=172.20.0.10 port=57272
2025-08-08 02:33:14 GMT [1567]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=57278
2025-08-08 02:33:14 GMT [1567]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:33:14 GMT [1567]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:33:14 GMT [1567]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.005 user=efm database=postgres host=172.20.0.10 port=57278
2025-08-08 02:33:17 GMT [1671]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=52930
2025-08-08 02:33:17 GMT [1671]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:33:17 GMT [1671]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:33:17 GMT [1671]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.033 user=efm database=postgres host=172.20.0.10 port=52930
2025-08-08 02:33:17 GMT [1674]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=52934
2025-08-08 02:33:17 GMT [1674]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:33:17 GMT [1674]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:33:17 GMT [1674]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.006 user=efm database=postgres host=172.20.0.10 port=52934
2025-08-08 02:33:18 GMT [1686]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:33:18 GMT [1686]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:33:18 GMT [1686]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:33:18 GMT [1686]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-08 02:33:19 GMT [1789]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=52942
2025-08-08 02:33:19 GMT [1789]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:33:19 GMT [1789]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:33:19 GMT [1789]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.035 user=efm database=postgres host=172.20.0.10 port=52942
2025-08-08 02:33:19 GMT [1791]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=52956
2025-08-08 02:33:19 GMT [1791]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:33:19 GMT [1791]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:33:19 GMT [1791]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.003 user=efm database=postgres host=172.20.0.10 port=52956
2025-08-08 02:33:29 GMT [1796]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:33:29 GMT [1796]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:33:29 GMT [1796]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-08 02:33:42 GMT [1192]: [7-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.999 user=efm database=postgres host=172.20.0.10 port=45298
2025-08-08 02:33:42 GMT [1797]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=53058
2025-08-08 02:33:42 GMT [1797]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:33:42 GMT [1797]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:33:48 GMT [1805]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:33:48 GMT [1805]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:33:48 GMT [1805]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:33:48 GMT [1805]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:34:09 GMT [1452]: [8-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:34:09 GMT [1452]: [9-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:34:10 GMT [1452]: [10-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:34:10 GMT [1452]: [11-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:34:11 GMT [1452]: [12-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:34:11 GMT [1452]: [13-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:34:11 GMT [1452]: [14-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:34:19 GMT [1821]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:34:19 GMT [1821]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:34:19 GMT [1821]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:34:19 GMT [1821]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-08 02:34:49 GMT [1830]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:34:49 GMT [1830]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:34:49 GMT [1830]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:34:49 GMT [1830]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:35:11 GMT [1452]: [15-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:35:11 GMT [1452]: [16-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:35:12 GMT [1452]: [17-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:35:12 GMT [1452]: [18-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:35:13 GMT [1452]: [19-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:35:13 GMT [1452]: [20-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:35:13 GMT [1452]: [21-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:35:19 GMT [1855]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:35:19 GMT [1855]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:35:19 GMT [1855]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:35:19 GMT [1855]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:35:22 GMT [1797]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.994 user=efm database=postgres host=172.20.0.10 port=53058
2025-08-08 02:35:22 GMT [1856]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=60824
2025-08-08 02:35:22 GMT [1856]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:35:22 GMT [1856]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:35:49 GMT [1864]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:35:49 GMT [1864]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:35:49 GMT [1864]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:35:49 GMT [1864]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:36:13 GMT [1452]: [22-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:36:13 GMT [1452]: [23-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:36:14 GMT [1452]: [24-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:36:14 GMT [1452]: [25-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:36:15 GMT [1452]: [26-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:36:15 GMT [1452]: [27-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:36:15 GMT [1452]: [28-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:36:19 GMT [1884]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:36:19 GMT [1884]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:36:19 GMT [1884]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:36:19 GMT [1884]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:36:49 GMT [1892]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:36:49 GMT [1892]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:36:49 GMT [1892]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:36:49 GMT [1892]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
2025-08-08 02:37:02 GMT [1856]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.993 user=efm database=postgres host=172.20.0.10 port=60824
2025-08-08 02:37:02 GMT [1894]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=34932
2025-08-08 02:37:02 GMT [1894]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:37:02 GMT [1894]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:37:15 GMT [1452]: [29-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:37:15 GMT [1452]: [30-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:37:16 GMT [1452]: [31-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:37:16 GMT [1452]: [32-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:37:17 GMT [1452]: [33-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:37:17 GMT [1452]: [34-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:37:17 GMT [1452]: [35-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:37:19 GMT [1913]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:37:19 GMT [1913]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:37:19 GMT [1913]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:37:19 GMT [1913]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:37:36 GMT [1920]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:37:36 GMT [1920]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:37:36 GMT [1920]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-08 02:37:36 GMT [1920]: [4-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.003 user=postgres database=postgres host=[local]
2025-08-08 02:37:49 GMT [1940]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:37:49 GMT [1940]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:37:49 GMT [1940]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:37:49 GMT [1940]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.003 user=postgres database=postgres host=[local]
2025-08-08 02:37:52 GMT [1947]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:37:52 GMT [1947]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:37:52 GMT [1947]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-08 02:37:52 GMT [1947]: [4-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
2025-08-08 02:38:07 GMT [1169]: [3-1] user=,db=,app=,client= LOG:  checkpoint starting: time
2025-08-08 02:38:08 GMT [1169]: [4-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.309 s, sync=0.012 s, total=0.333 s; sync files=4, longest=0.006 s, average=0.003 s; distance=1 kB, estimate=14745 kB; lsn=0/A000588, redo lsn=0/A000530
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:38:17 GMT [1452]: [36-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:38:17 GMT [1452]: [37-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:38:18 GMT [1452]: [38-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:38:18 GMT [1452]: [39-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:38:19 GMT [1961]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:38:19 GMT [1961]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:38:19 GMT [1961]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:38:19 GMT [1961]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:38:19 GMT [1452]: [40-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:38:19 GMT [1452]: [41-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:38:19 GMT [1452]: [42-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:38:42 GMT [1894]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.994 user=efm database=postgres host=172.20.0.10 port=34932
2025-08-08 02:38:42 GMT [1965]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=45584
2025-08-08 02:38:42 GMT [1965]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:38:42 GMT [1965]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:38:49 GMT [1973]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:38:49 GMT [1973]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:38:49 GMT [1973]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:38:49 GMT [1973]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:39:19 GMT [1983]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:39:19 GMT [1983]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:39:19 GMT [1983]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:39:19 GMT [1983]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:39:19 GMT [1452]: [43-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:39:19 GMT [1452]: [44-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:39:20 GMT [1452]: [45-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:39:20 GMT [1452]: [46-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:39:21 GMT [1452]: [47-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:39:21 GMT [1452]: [48-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:39:21 GMT [1452]: [49-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:39:49 GMT [1999]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:39:49 GMT [1999]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:39:49 GMT [1999]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:39:49 GMT [1999]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:40:19 GMT [2008]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:40:19 GMT [2008]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:40:19 GMT [2008]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:40:19 GMT [2008]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:40:21 GMT [1452]: [50-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:40:21 GMT [1452]: [51-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:40:22 GMT [1965]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.994 user=efm database=postgres host=172.20.0.10 port=45584
2025-08-08 02:40:22 GMT [2011]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=36362
2025-08-08 02:40:22 GMT [2011]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:40:22 GMT [2011]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:40:22 GMT [1452]: [52-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:40:22 GMT [1452]: [53-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:40:23 GMT [1452]: [54-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:40:23 GMT [1452]: [55-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:40:23 GMT [1452]: [56-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:40:50 GMT [2024]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:40:50 GMT [2024]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:40:50 GMT [2024]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:40:50 GMT [2024]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:41:20 GMT [2035]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:41:20 GMT [2035]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:41:20 GMT [2035]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:41:20 GMT [2035]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:41:24 GMT [1452]: [57-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:41:24 GMT [1452]: [58-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:41:25 GMT [1452]: [59-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:41:25 GMT [1452]: [60-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:41:26 GMT [1452]: [61-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:41:26 GMT [1452]: [62-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:41:26 GMT [1452]: [63-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:41:50 GMT [2051]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:41:50 GMT [2051]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:41:50 GMT [2051]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:41:50 GMT [2051]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:42:02 GMT [2011]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.993 user=efm database=postgres host=172.20.0.10 port=36362
2025-08-08 02:42:02 GMT [2053]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=52358
2025-08-08 02:42:02 GMT [2053]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:42:02 GMT [2053]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:42:20 GMT [2062]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:42:20 GMT [2062]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:42:20 GMT [2062]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:42:20 GMT [2062]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:42:26 GMT [1452]: [64-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:42:26 GMT [1452]: [65-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:42:27 GMT [1452]: [66-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:42:27 GMT [1452]: [67-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:42:28 GMT [1452]: [68-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:42:28 GMT [1452]: [69-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:42:28 GMT [1452]: [70-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:42:50 GMT [2075]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:42:50 GMT [2075]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:42:50 GMT [2075]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:42:50 GMT [2075]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:43:20 GMT [2086]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:43:20 GMT [2086]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:43:20 GMT [2086]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:43:20 GMT [2086]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:43:28 GMT [1452]: [71-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:43:28 GMT [1452]: [72-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:43:29 GMT [1452]: [73-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:43:29 GMT [1452]: [74-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:43:30 GMT [1452]: [75-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:43:30 GMT [1452]: [76-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:43:30 GMT [1452]: [77-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:43:42 GMT [2053]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.989 user=efm database=postgres host=172.20.0.10 port=52358
2025-08-08 02:43:42 GMT [2096]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=38004
2025-08-08 02:43:42 GMT [2096]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:43:42 GMT [2096]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:43:50 GMT [2104]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:43:50 GMT [2104]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:43:50 GMT [2104]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:43:50 GMT [2104]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:44:20 GMT [2113]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:44:20 GMT [2113]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:44:20 GMT [2113]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:44:20 GMT [2113]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:44:30 GMT [1452]: [78-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:44:30 GMT [1452]: [79-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:44:31 GMT [1452]: [80-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:44:31 GMT [1452]: [81-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:44:32 GMT [1452]: [82-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:44:32 GMT [1452]: [83-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:44:32 GMT [1452]: [84-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:44:50 GMT [2129]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:44:50 GMT [2129]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:44:50 GMT [2129]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:44:50 GMT [2129]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:45:20 GMT [2138]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:45:20 GMT [2138]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:45:20 GMT [2138]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:45:20 GMT [2138]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
2025-08-08 02:45:22 GMT [2096]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.997 user=efm database=postgres host=172.20.0.10 port=38004
2025-08-08 02:45:22 GMT [2139]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=43582
2025-08-08 02:45:22 GMT [2139]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:45:22 GMT [2139]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:45:32 GMT [1452]: [85-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:45:32 GMT [1452]: [86-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:45:33 GMT [1452]: [87-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:45:33 GMT [1452]: [88-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:45:34 GMT [1452]: [89-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:45:34 GMT [1452]: [90-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:45:34 GMT [1452]: [91-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:45:50 GMT [2153]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:45:50 GMT [2153]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:45:50 GMT [2153]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:45:50 GMT [2153]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:46:20 GMT [2163]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:46:20 GMT [2163]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:46:20 GMT [2163]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:46:20 GMT [2163]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:46:34 GMT [1452]: [92-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:46:34 GMT [1452]: [93-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:46:35 GMT [1452]: [94-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:46:35 GMT [1452]: [95-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:46:36 GMT [1452]: [96-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:46:36 GMT [1452]: [97-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:46:36 GMT [1452]: [98-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:46:50 GMT [2177]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:46:50 GMT [2177]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:46:50 GMT [2177]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:46:50 GMT [2177]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
2025-08-08 02:47:02 GMT [2139]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.992 user=efm database=postgres host=172.20.0.10 port=43582
2025-08-08 02:47:02 GMT [2179]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=60252
2025-08-08 02:47:02 GMT [2179]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:47:02 GMT [2179]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:47:20 GMT [2188]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:47:20 GMT [2188]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:47:20 GMT [2188]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:47:20 GMT [2188]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:47:36 GMT [1452]: [99-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:47:36 GMT [1452]: [100-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:47:37 GMT [1452]: [101-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:47:37 GMT [1452]: [102-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:47:38 GMT [1452]: [103-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:47:38 GMT [1452]: [104-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:47:38 GMT [1452]: [105-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:47:50 GMT [2204]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:47:50 GMT [2204]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:47:50 GMT [2204]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:47:50 GMT [2204]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:48:21 GMT [2213]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:48:21 GMT [2213]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:48:21 GMT [2213]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:48:21 GMT [2213]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:48:38 GMT [1452]: [106-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:48:38 GMT [1452]: [107-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:48:39 GMT [1452]: [108-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:48:39 GMT [1452]: [109-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:48:40 GMT [1452]: [110-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:48:40 GMT [1452]: [111-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:48:40 GMT [1452]: [112-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:48:42 GMT [2179]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.994 user=efm database=postgres host=172.20.0.10 port=60252
2025-08-08 02:48:42 GMT [2222]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=53884
2025-08-08 02:48:42 GMT [2222]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:48:42 GMT [2222]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:48:51 GMT [2230]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:48:51 GMT [2230]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:48:51 GMT [2230]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:48:51 GMT [2230]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:49:21 GMT [2239]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:49:21 GMT [2239]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:49:21 GMT [2239]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:49:21 GMT [2239]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:49:40 GMT [1452]: [113-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:49:40 GMT [1452]: [114-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:49:41 GMT [1452]: [115-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:49:41 GMT [1452]: [116-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:49:42 GMT [1452]: [117-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:49:42 GMT [1452]: [118-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:49:42 GMT [1452]: [119-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:49:51 GMT [2258]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:49:51 GMT [2258]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:49:51 GMT [2258]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:49:51 GMT [2258]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:50:21 GMT [2268]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:50:21 GMT [2268]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:50:21 GMT [2268]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:50:21 GMT [2268]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:50:22 GMT [2222]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.986 user=efm database=postgres host=172.20.0.10 port=53884
2025-08-08 02:50:22 GMT [2269]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=38096
2025-08-08 02:50:22 GMT [2269]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:50:22 GMT [2269]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:50:42 GMT [1452]: [120-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:50:42 GMT [1452]: [121-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:50:43 GMT [1452]: [122-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:50:43 GMT [1452]: [123-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:50:44 GMT [1452]: [124-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:50:44 GMT [1452]: [125-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:50:44 GMT [1452]: [126-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:50:51 GMT [2284]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:50:51 GMT [2284]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:50:51 GMT [2284]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:50:51 GMT [2284]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-08 02:51:21 GMT [2295]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:51:21 GMT [2295]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:51:21 GMT [2295]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:51:21 GMT [2295]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:51:44 GMT [1452]: [127-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:51:44 GMT [1452]: [128-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:51:45 GMT [1452]: [129-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:51:45 GMT [1452]: [130-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:51:46 GMT [1452]: [131-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:51:46 GMT [1452]: [132-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:51:46 GMT [1452]: [133-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:51:51 GMT [2309]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:51:51 GMT [2309]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:51:51 GMT [2309]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:51:51 GMT [2309]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:52:02 GMT [2269]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.995 user=efm database=postgres host=172.20.0.10 port=38096
2025-08-08 02:52:02 GMT [2311]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=56520
2025-08-08 02:52:02 GMT [2311]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:52:02 GMT [2311]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:52:21 GMT [2320]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:52:21 GMT [2320]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:52:21 GMT [2320]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:52:21 GMT [2320]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:52:46 GMT [1452]: [134-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:52:46 GMT [1452]: [135-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:52:47 GMT [1452]: [136-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:52:47 GMT [1452]: [137-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:52:48 GMT [1452]: [138-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:52:48 GMT [1452]: [139-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:52:48 GMT [1452]: [140-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:52:51 GMT [2335]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:52:51 GMT [2335]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:52:51 GMT [2335]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:52:51 GMT [2335]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:53:21 GMT [2344]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:53:21 GMT [2344]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:53:21 GMT [2344]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:53:21 GMT [2344]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
2025-08-08 02:53:42 GMT [2311]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.983 user=efm database=postgres host=172.20.0.10 port=56520
2025-08-08 02:53:42 GMT [2346]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=58614
2025-08-08 02:53:42 GMT [2346]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:53:42 GMT [2346]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:53:48 GMT [1452]: [141-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:53:48 GMT [1452]: [142-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:53:49 GMT [1452]: [143-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:53:49 GMT [1452]: [144-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:53:50 GMT [1452]: [145-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:53:50 GMT [1452]: [146-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:53:50 GMT [1452]: [147-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:53:51 GMT [2360]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:53:51 GMT [2360]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:53:51 GMT [2360]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:53:51 GMT [2360]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:54:21 GMT [2369]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:54:21 GMT [2369]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:54:21 GMT [2369]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:54:21 GMT [2369]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:54:50 GMT [1452]: [148-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:54:50 GMT [1452]: [149-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:54:51 GMT [2379]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:54:51 GMT [2379]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:54:51 GMT [2379]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:54:51 GMT [2379]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:54:51 GMT [1452]: [150-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:54:51 GMT [1452]: [151-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:54:52 GMT [1452]: [152-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:54:52 GMT [1452]: [153-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:54:52 GMT [1452]: [154-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:55:21 GMT [2393]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:55:21 GMT [2393]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:55:21 GMT [2393]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:55:21 GMT [2393]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
2025-08-08 02:55:22 GMT [2346]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.992 user=efm database=postgres host=172.20.0.10 port=58614
2025-08-08 02:55:22 GMT [2395]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=34628
2025-08-08 02:55:22 GMT [2395]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:55:22 GMT [2395]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:55:52 GMT [2404]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:55:52 GMT [2404]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:55:52 GMT [2404]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:55:52 GMT [2404]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:55:53 GMT [1452]: [155-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:55:53 GMT [1452]: [156-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:55:54 GMT [1452]: [157-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:55:54 GMT [1452]: [158-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:55:55 GMT [1452]: [159-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:55:55 GMT [1452]: [160-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:55:55 GMT [1452]: [161-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:56:00 GMT [1457]: [4-1] user=replicator,db=[unknown],app=efm_cluster_standby,client=172.20.0.11 LOG:  unexpected EOF on standby connection
2025-08-08 02:56:00 GMT [1457]: [5-1] user=replicator,db=[unknown],app=efm_cluster_standby,client=172.20.0.11 STATEMENT:  START_REPLICATION 0/A000000 TIMELINE 7
2025-08-08 02:56:00 GMT [1457]: [6-1] user=replicator,db=[unknown],app=efm_cluster_standby,client=172.20.0.11 LOG:  disconnection: session time: 0:22:53.421 user=replicator database= host=172.20.0.11 port=39086
