2025-08-08 02:17:16 GMT [9]: [3-1] user=,db=,app=,client= LOG:  starting PostgreSQL 17.5 (Debian 17.5-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2025-08-08 02:17:16 GMT [9]: [4-1] user=,db=,app=,client= LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-08-08 02:17:16 GMT [9]: [5-1] user=,db=,app=,client= LOG:  listening on IPv6 address "::", port 5432
2025-08-08 02:17:16 GMT [9]: [6-1] user=,db=,app=,client= LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-08-08 02:17:16 GMT [15]: [1-1] user=,db=,app=,client= LOG:  database system was interrupted while in recovery at log time 2025-08-08 02:14:27 GMT
2025-08-08 02:17:16 GMT [15]: [2-1] user=,db=,app=,client= HINT:  If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.
2025-08-08 02:17:16 GMT [15]: [3-1] user=,db=,app=,client= LOG:  entering standby mode
2025-08-08 02:17:16 GMT [15]: [4-1] user=,db=,app=,client= LOG:  consistent recovery state reached at 0/70000A0
2025-08-08 02:17:16 GMT [9]: [7-1] user=,db=,app=,client= LOG:  database system is ready to accept read-only connections
2025-08-08 02:17:16 GMT [15]: [5-1] user=,db=,app=,client= LOG:  redo starts at 0/70000A0
2025-08-08 02:17:16 GMT [15]: [6-1] user=,db=,app=,client= LOG:  invalid record length at 0/7000218: expected at least 24, got 0
2025-08-08 02:17:18 GMT [18]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=::1 LOG:  connection received: host=::1 port=56526
2025-08-08 02:17:18 GMT [20]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:17:18 GMT [20]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:17:18 GMT [20]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-08 02:17:18 GMT [20]: [4-1] user=postgres,db=postgres,app=psql,client=[local] ERROR:  cannot execute CREATE DATABASE in a read-only transaction
2025-08-08 02:17:18 GMT [20]: [5-1] user=postgres,db=postgres,app=psql,client=[local] STATEMENT:  CREATE DATABASE testdb
2025-08-08 02:17:18 GMT [20]: [6-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.003 user=postgres database=postgres host=[local]
2025-08-08 02:17:18 GMT [22]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:17:18 GMT [22]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:17:18 GMT [22]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-08 02:17:18 GMT [22]: [4-1] user=postgres,db=postgres,app=psql,client=[local] ERROR:  cannot execute CREATE ROLE in a read-only transaction
2025-08-08 02:17:18 GMT [22]: [5-1] user=postgres,db=postgres,app=psql,client=[local] STATEMENT:  CREATE USER replicator WITH REPLICATION LOGIN PASSWORD 'replicator'
2025-08-08 02:17:18 GMT [22]: [6-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:17:18 GMT [24]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:17:18 GMT [24]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:17:18 GMT [24]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-08 02:17:18 GMT [24]: [4-1] user=postgres,db=postgres,app=psql,client=[local] ERROR:  cannot execute CREATE ROLE in a read-only transaction
2025-08-08 02:17:18 GMT [24]: [5-1] user=postgres,db=postgres,app=psql,client=[local] STATEMENT:  CREATE USER efm WITH LOGIN PASSWORD 'efm'
2025-08-08 02:17:18 GMT [24]: [6-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-08 02:17:18 GMT [26]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:17:18 GMT [26]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:17:18 GMT [26]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-08 02:17:18 GMT [26]: [4-1] user=postgres,db=postgres,app=psql,client=[local] ERROR:  cannot execute GRANT in a read-only transaction
2025-08-08 02:17:18 GMT [26]: [5-1] user=postgres,db=postgres,app=psql,client=[local] STATEMENT:  GRANT ALL PRIVILEGES ON DATABASE testdb TO efm
2025-08-08 02:17:18 GMT [26]: [6-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-08 02:17:19 GMT [158]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=43010
2025-08-08 02:17:19 GMT [158]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:17:19 GMT [158]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:17:19 GMT [16]: [1-1] user=,db=,app=,client= FATAL:  could not connect to the primary server: connection to server at "172.20.0.11", port 5432 failed: No route to host
		Is the server running on that host and accepting TCP/IP connections?
2025-08-08 02:17:22 GMT [200]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=43024
2025-08-08 02:17:22 GMT [200]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:17:22 GMT [200]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:17:22 GMT [200]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.004 user=efm database=postgres host=172.20.0.10 port=43024
2025-08-08 02:17:22 GMT [185]: [1-1] user=,db=,app=,client= FATAL:  could not connect to the primary server: connection to server at "172.20.0.11", port 5432 failed: No route to host
		Is the server running on that host and accepting TCP/IP connections?
2025-08-08 02:17:22 GMT [15]: [7-1] user=,db=,app=,client= LOG:  waiting for WAL to become available at 0/7000230
2025-08-08 02:17:27 GMT [204]: [1-1] user=,db=,app=,client= FATAL:  could not connect to the primary server: connection to server at "172.20.0.11", port 5432 failed: No route to host
		Is the server running on that host and accepting TCP/IP connections?
2025-08-08 02:17:27 GMT [15]: [8-1] user=,db=,app=,client= LOG:  waiting for WAL to become available at 0/7000230
2025-08-08 02:17:32 GMT [205]: [1-1] user=,db=,app=,client= FATAL:  could not connect to the primary server: connection to server at "172.20.0.11", port 5432 failed: No route to host
		Is the server running on that host and accepting TCP/IP connections?
2025-08-08 02:17:32 GMT [15]: [9-1] user=,db=,app=,client= LOG:  waiting for WAL to become available at 0/7000230
2025-08-08 02:17:37 GMT [206]: [1-1] user=,db=,app=,client= FATAL:  could not connect to the primary server: connection to server at "172.20.0.11", port 5432 failed: No route to host
		Is the server running on that host and accepting TCP/IP connections?
2025-08-08 02:17:37 GMT [15]: [10-1] user=,db=,app=,client= LOG:  waiting for WAL to become available at 0/7000230
2025-08-08 02:17:42 GMT [207]: [1-1] user=,db=,app=,client= FATAL:  could not connect to the primary server: connection to server at "172.20.0.11", port 5432 failed: No route to host
		Is the server running on that host and accepting TCP/IP connections?
2025-08-08 02:17:42 GMT [15]: [11-1] user=,db=,app=,client= LOG:  waiting for WAL to become available at 0/7000230
2025-08-08 02:17:46 GMT [216]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:17:46 GMT [216]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:17:46 GMT [216]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:17:46 GMT [216]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-08 02:17:47 GMT [208]: [1-1] user=,db=,app=,client= FATAL:  could not connect to the primary server: connection to server at "172.20.0.11", port 5432 failed: Connection refused
		Is the server running on that host and accepting TCP/IP connections?
2025-08-08 02:17:47 GMT [15]: [12-1] user=,db=,app=,client= LOG:  waiting for WAL to become available at 0/7000230
2025-08-08 02:17:49 GMT [217]: [1-1] user=,db=,app=,client= FATAL:  could not connect to the primary server: connection to server at "172.20.0.11", port 5432 failed: Connection refused
		Is the server running on that host and accepting TCP/IP connections?
2025-08-08 02:17:49 GMT [15]: [13-1] user=,db=,app=,client= LOG:  waiting for WAL to become available at 0/7000230
2025-08-08 02:17:54 GMT [218]: [1-1] user=,db=,app=,client= FATAL:  could not connect to the primary server: connection to server at "172.20.0.11", port 5432 failed: Connection refused
		Is the server running on that host and accepting TCP/IP connections?
2025-08-08 02:17:54 GMT [15]: [14-1] user=,db=,app=,client= LOG:  waiting for WAL to become available at 0/7000230
2025-08-08 02:17:59 GMT [219]: [1-1] user=,db=,app=,client= FATAL:  could not connect to the primary server: connection to server at "172.20.0.11", port 5432 failed: Connection refused
		Is the server running on that host and accepting TCP/IP connections?
2025-08-08 02:17:59 GMT [15]: [15-1] user=,db=,app=,client= LOG:  waiting for WAL to become available at 0/7000230
2025-08-08 02:18:04 GMT [220]: [1-1] user=,db=,app=,client= LOG:  started streaming WAL from primary at 0/7000000 on timeline 4
2025-08-08 02:18:05 GMT [229]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=53140
2025-08-08 02:18:05 GMT [229]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:18:05 GMT [229]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:18:05 GMT [229]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.11 LOG:  disconnection: session time: 0:00:00.004 user=efm database=postgres host=172.20.0.11 port=53140
2025-08-08 02:18:16 GMT [238]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:18:16 GMT [238]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:18:16 GMT [238]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:18:16 GMT [238]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:18:18 GMT [245]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.12 LOG:  connection received: host=172.20.0.12 port=47614
2025-08-08 02:18:18 GMT [245]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.12 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:18:18 GMT [245]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.12 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:18:18 GMT [245]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.12 LOG:  disconnection: session time: 0:00:00.004 user=efm database=postgres host=172.20.0.12 port=47614
2025-08-08 02:18:46 GMT [253]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:18:46 GMT [253]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:18:46 GMT [253]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:18:46 GMT [253]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:19:02 GMT [158]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:43.234 user=efm database=postgres host=172.20.0.10 port=43010
2025-08-08 02:19:02 GMT [255]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=36886
2025-08-08 02:19:02 GMT [255]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:19:02 GMT [255]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:19:17 GMT [264]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:19:17 GMT [264]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:19:17 GMT [264]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:19:17 GMT [264]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-08 02:19:47 GMT [273]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:19:47 GMT [273]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:19:47 GMT [273]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:19:47 GMT [273]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:20:17 GMT [282]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:20:17 GMT [282]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:20:17 GMT [282]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:20:17 GMT [282]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:20:42 GMT [255]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:40.001 user=efm database=postgres host=172.20.0.10 port=36886
2025-08-08 02:20:42 GMT [284]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=59414
2025-08-08 02:20:42 GMT [284]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:20:42 GMT [284]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:20:47 GMT [292]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:20:47 GMT [292]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:20:47 GMT [292]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:20:47 GMT [292]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-08 02:21:17 GMT [301]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:21:17 GMT [301]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:21:17 GMT [301]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:21:17 GMT [301]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
2025-08-08 02:21:47 GMT [310]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:21:47 GMT [310]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:21:47 GMT [310]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:21:47 GMT [310]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:22:16 GMT [13]: [1-1] user=,db=,app=,client= LOG:  restartpoint starting: time
2025-08-08 02:22:16 GMT [13]: [2-1] user=,db=,app=,client= LOG:  restartpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 2 recycled; write=0.003 s, sync=0.001 s, total=0.033 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=0 kB; lsn=0/7000218, redo lsn=0/7000218
2025-08-08 02:22:16 GMT [13]: [3-1] user=,db=,app=,client= LOG:  recovery restart point at 0/7000218
2025-08-08 02:22:17 GMT [318]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:22:17 GMT [318]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:22:17 GMT [318]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:22:17 GMT [318]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:22:22 GMT [284]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.992 user=efm database=postgres host=172.20.0.10 port=59414
2025-08-08 02:22:22 GMT [319]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=42078
2025-08-08 02:22:22 GMT [319]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:22:22 GMT [319]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:22:47 GMT [328]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:22:47 GMT [328]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:22:47 GMT [328]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:22:47 GMT [328]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
2025-08-08 02:23:17 GMT [337]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:23:17 GMT [337]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:23:17 GMT [337]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:23:17 GMT [337]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-08 02:23:47 GMT [346]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:23:47 GMT [346]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:23:47 GMT [346]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:23:47 GMT [346]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:24:02 GMT [319]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:40.001 user=efm database=postgres host=172.20.0.10 port=42078
2025-08-08 02:24:02 GMT [347]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=47370
2025-08-08 02:24:02 GMT [347]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:24:02 GMT [347]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:24:17 GMT [355]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:24:17 GMT [355]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:24:17 GMT [355]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:24:17 GMT [355]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:24:47 GMT [365]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:24:47 GMT [365]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:24:47 GMT [365]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:24:47 GMT [365]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:25:17 GMT [373]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:25:17 GMT [373]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:25:17 GMT [373]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:25:17 GMT [373]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:25:42 GMT [347]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.982 user=efm database=postgres host=172.20.0.10 port=47370
2025-08-08 02:25:42 GMT [377]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=56726
2025-08-08 02:25:42 GMT [377]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:25:42 GMT [377]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:25:47 GMT [385]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:25:47 GMT [385]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:25:47 GMT [385]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:25:47 GMT [385]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-08 02:26:17 GMT [395]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:26:17 GMT [395]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:26:17 GMT [395]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:26:17 GMT [395]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-08 02:26:48 GMT [415]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:26:48 GMT [415]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:26:48 GMT [415]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:26:48 GMT [415]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
2025-08-08 02:27:18 GMT [424]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:27:18 GMT [424]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:27:18 GMT [424]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:27:18 GMT [424]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
2025-08-08 02:27:22 GMT [377]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.988 user=efm database=postgres host=172.20.0.10 port=56726
2025-08-08 02:27:22 GMT [426]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=51904
2025-08-08 02:27:22 GMT [426]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:27:22 GMT [426]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:27:48 GMT [441]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:27:48 GMT [441]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:27:48 GMT [441]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:27:48 GMT [441]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:28:18 GMT [457]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:28:18 GMT [457]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:28:18 GMT [457]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:28:18 GMT [457]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:28:48 GMT [471]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:28:48 GMT [471]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:28:48 GMT [471]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:28:48 GMT [471]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
2025-08-08 02:28:49 GMT [575]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=40678
2025-08-08 02:28:49 GMT [575]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:28:49 GMT [575]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:28:49 GMT [575]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.032 user=efm database=postgres host=172.20.0.10 port=40678
2025-08-08 02:28:49 GMT [577]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=40690
2025-08-08 02:28:49 GMT [577]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:28:49 GMT [577]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:28:49 GMT [577]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.003 user=efm database=postgres host=172.20.0.10 port=40690
2025-08-08 02:28:49 GMT [578]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=40694
2025-08-08 02:28:49 GMT [578]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:28:49 GMT [578]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:28:49 GMT [578]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.003 user=efm database=postgres host=172.20.0.10 port=40694
2025-08-08 02:28:56 GMT [581]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=58868
2025-08-08 02:28:56 GMT [581]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:28:56 GMT [581]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:28:56 GMT [581]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.11 LOG:  disconnection: session time: 0:00:00.033 user=efm database=postgres host=172.20.0.11 port=58868
2025-08-08 02:28:56 GMT [582]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=58882
2025-08-08 02:28:56 GMT [582]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:28:56 GMT [582]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:28:56 GMT [582]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.11 LOG:  disconnection: session time: 0:00:00.003 user=efm database=postgres host=172.20.0.11 port=58882
2025-08-08 02:28:56 GMT [583]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=58890
2025-08-08 02:28:56 GMT [583]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:28:56 GMT [583]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:28:56 GMT [583]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.11 LOG:  disconnection: session time: 0:00:00.003 user=efm database=postgres host=172.20.0.11 port=58890
2025-08-08 02:29:02 GMT [426]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.993 user=efm database=postgres host=172.20.0.10 port=51904
2025-08-08 02:29:02 GMT [584]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=40534
2025-08-08 02:29:02 GMT [584]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:29:02 GMT [584]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:29:08 GMT [684]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=58496
2025-08-08 02:29:08 GMT [684]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:29:08 GMT [684]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:29:08 GMT [684]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.028 user=efm database=postgres host=172.20.0.10 port=58496
2025-08-08 02:29:08 GMT [689]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=58932
2025-08-08 02:29:08 GMT [689]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:29:08 GMT [689]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:29:08 GMT [689]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.11 LOG:  disconnection: session time: 0:00:00.004 user=efm database=postgres host=172.20.0.11 port=58932
2025-08-08 02:29:08 GMT [220]: [2-1] user=,db=,app=,client= LOG:  replication terminated by primary server
2025-08-08 02:29:08 GMT [220]: [3-1] user=,db=,app=,client= DETAIL:  End of WAL reached on timeline 4 at 0/80000A0.
2025-08-08 02:29:08 GMT [220]: [4-1] user=,db=,app=,client= FATAL:  could not send end-of-streaming message to primary: server closed the connection unexpectedly
		This probably means the server terminated abnormally
		before or while processing the request.
	no COPY in progress
2025-08-08 02:29:08 GMT [15]: [16-1] user=,db=,app=,client= LOG:  record with incorrect prev-link 0/1000028 at 0/80000A0
2025-08-08 02:29:08 GMT [690]: [1-1] user=,db=,app=,client= FATAL:  could not connect to the primary server: connection to server at "172.20.0.11", port 5432 failed: FATAL:  the database system is shutting down
2025-08-08 02:29:08 GMT [15]: [17-1] user=,db=,app=,client= LOG:  waiting for WAL to become available at 0/80000B8
2025-08-08 02:29:12 GMT [15]: [18-1] user=,db=,app=,client= LOG:  received promote request
2025-08-08 02:29:12 GMT [15]: [19-1] user=,db=,app=,client= LOG:  redo done at 0/8000028 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 715.34 s
2025-08-08 02:29:12 GMT [15]: [20-1] user=,db=,app=,client= LOG:  selected new timeline ID: 5
2025-08-08 02:29:12 GMT [584]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 ERROR:  standby promotion is ongoing
2025-08-08 02:29:12 GMT [584]: [5-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 HINT:  pg_wal_replay_resume() cannot be executed after promotion is triggered.
2025-08-08 02:29:12 GMT [584]: [6-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 STATEMENT:  select pg_wal_replay_resume()
2025-08-08 02:29:12 GMT [15]: [21-1] user=,db=,app=,client= LOG:  archive recovery complete
2025-08-08 02:29:12 GMT [13]: [4-1] user=,db=,app=,client= LOG:  checkpoint starting: force
2025-08-08 02:29:12 GMT [9]: [8-1] user=,db=,app=,client= LOG:  database system is ready to accept connections
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:29:12 GMT [717]: [1-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:29:12 GMT [717]: [2-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:29:12 GMT [721]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=58934
2025-08-08 02:29:12 GMT [721]: [2-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="replicator" method=md5 (/var/lib/postgresql/data/pg_hba.conf:18)
2025-08-08 02:29:12 GMT [721]: [3-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  replication connection authorized: user=replicator application_name=efm_cluster_standby
2025-08-08 02:29:12 GMT [721]: [4-1] user=replicator,db=[unknown],app=efm_cluster_standby,client=172.20.0.11 LOG:  disconnection: session time: 0:00:00.006 user=replicator database= host=172.20.0.11 port=58934
2025-08-08 02:29:12 GMT [13]: [5-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.007 s, total=0.015 s; sync files=2, longest=0.006 s, average=0.004 s; distance=16383 kB, estimate=16383 kB; lsn=0/8000130, redo lsn=0/80000D8
2025-08-08 02:29:12 GMT [722]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=58946
2025-08-08 02:29:12 GMT [722]: [2-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="replicator" method=md5 (/var/lib/postgresql/data/pg_hba.conf:18)
2025-08-08 02:29:12 GMT [722]: [3-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 LOG:  replication connection authorized: user=replicator application_name=efm_cluster_standby
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:29:13 GMT [717]: [3-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:29:13 GMT [717]: [4-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:29:14 GMT [717]: [5-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:29:14 GMT [717]: [6-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:29:14 GMT [717]: [7-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:29:18 GMT [825]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:29:18 GMT [825]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:29:18 GMT [825]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:29:18 GMT [825]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:29:19 GMT [928]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=60426
2025-08-08 02:29:19 GMT [928]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:29:19 GMT [928]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:29:19 GMT [928]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.036 user=efm database=postgres host=172.20.0.10 port=60426
2025-08-08 02:29:19 GMT [930]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=60430
2025-08-08 02:29:19 GMT [930]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:29:19 GMT [930]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:29:19 GMT [930]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.003 user=efm database=postgres host=172.20.0.10 port=60430
2025-08-08 02:29:25 GMT [936]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=43622
2025-08-08 02:29:25 GMT [936]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:29:25 GMT [936]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:29:25 GMT [936]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.11 LOG:  disconnection: session time: 0:00:00.036 user=efm database=postgres host=172.20.0.11 port=43622
2025-08-08 02:29:25 GMT [937]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=43624
2025-08-08 02:29:25 GMT [937]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:29:25 GMT [937]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.11 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:29:25 GMT [937]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.11 LOG:  disconnection: session time: 0:00:00.006 user=efm database=postgres host=172.20.0.11 port=43624
2025-08-08 02:29:48 GMT [945]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:29:48 GMT [945]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:29:48 GMT [945]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:29:48 GMT [945]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.002 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:30:14 GMT [717]: [8-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:30:14 GMT [717]: [9-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:30:15 GMT [717]: [10-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:30:15 GMT [717]: [11-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:30:16 GMT [717]: [12-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:30:16 GMT [717]: [13-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:30:16 GMT [717]: [14-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:30:18 GMT [960]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:30:18 GMT [960]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:30:18 GMT [960]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:30:18 GMT [960]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.000 user=postgres database=postgres host=[local]
2025-08-08 02:30:42 GMT [584]: [7-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:39.985 user=efm database=postgres host=172.20.0.10 port=40534
2025-08-08 02:30:42 GMT [962]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=46070
2025-08-08 02:30:42 GMT [962]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:30:42 GMT [962]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:30:48 GMT [970]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:30:48 GMT [970]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:30:48 GMT [970]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:30:48 GMT [970]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:31:16 GMT [717]: [15-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:31:16 GMT [717]: [16-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:31:17 GMT [717]: [17-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:31:17 GMT [717]: [18-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:31:18 GMT [717]: [19-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:31:18 GMT [717]: [20-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:31:18 GMT [717]: [21-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:31:18 GMT [986]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:31:18 GMT [986]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:31:18 GMT [986]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:31:18 GMT [986]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:31:42 GMT [999]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:31:42 GMT [999]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:31:42 GMT [999]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=psql
2025-08-08 02:31:48 GMT [1007]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=[local] LOG:  connection received: host=[local]
2025-08-08 02:31:48 GMT [1007]: [2-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authenticated: identity="postgres" method=peer (/var/lib/postgresql/data/pg_hba.conf:7)
2025-08-08 02:31:48 GMT [1007]: [3-1] user=postgres,db=postgres,app=[unknown],client=[local] LOG:  connection authorized: user=postgres database=postgres application_name=pg_isready
2025-08-08 02:31:48 GMT [1007]: [4-1] user=postgres,db=postgres,app=pg_isready,client=[local] LOG:  disconnection: session time: 0:00:00.001 user=postgres database=postgres host=[local]
2025-08-08 02:31:53 GMT [999]: [4-1] user=postgres,db=postgres,app=psql,client=[local] LOG:  disconnection: session time: 0:00:11.509 user=postgres database=postgres host=[local]
2025-08-08 02:31:59 GMT [1109]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=45246
2025-08-08 02:31:59 GMT [1109]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:31:59 GMT [1109]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:31:59 GMT [1109]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.026 user=efm database=postgres host=172.20.0.10 port=45246
2025-08-08 02:31:59 GMT [962]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:01:16.552 user=efm database=postgres host=172.20.0.10 port=46070
2025-08-08 02:31:59 GMT [1114]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.10 LOG:  connection received: host=172.20.0.10 port=45258
2025-08-08 02:31:59 GMT [1114]: [2-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authenticated: identity="efm" method=md5 (/var/lib/postgresql/data/pg_hba.conf:15)
2025-08-08 02:31:59 GMT [1114]: [3-1] user=efm,db=postgres,app=[unknown],client=172.20.0.10 LOG:  connection authorized: user=efm database=postgres
2025-08-08 02:31:59 GMT [1114]: [4-1] user=efm,db=postgres,app=efm-5.0,client=172.20.0.10 LOG:  disconnection: session time: 0:00:00.001 user=efm database=postgres host=172.20.0.10 port=45258
2025-08-08 02:31:59 GMT [9]: [9-1] user=,db=,app=,client= LOG:  received fast shutdown request
2025-08-08 02:31:59 GMT [9]: [10-1] user=,db=,app=,client= LOG:  aborting any active transactions
2025-08-08 02:31:59 GMT [9]: [11-1] user=,db=,app=,client= LOG:  background worker "logical replication launcher" (PID 718) exited with exit code 1
2025-08-08 02:31:59 GMT [13]: [6-1] user=,db=,app=,client= LOG:  shutting down
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:31:59 GMT [717]: [22-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:31:59 GMT [717]: [23-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:31:59 GMT [13]: [7-1] user=,db=,app=,client= LOG:  checkpoint starting: shutdown immediate
2025-08-08 02:31:59 GMT [13]: [8-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.013 s, total=0.034 s; sync files=4, longest=0.008 s, average=0.004 s; distance=16383 kB, estimate=16383 kB; lsn=0/9000028, redo lsn=0/9000028
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:31:59 GMT [717]: [24-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:31:59 GMT [717]: [25-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:31:59 GMT [722]: [4-1] user=replicator,db=[unknown],app=efm_cluster_standby,client=172.20.0.11 LOG:  disconnection: session time: 0:02:47.169 user=replicator database= host=172.20.0.11 port=58946
2025-08-08 02:31:59 GMT [1135]: [1-1] user=[unknown],db=[unknown],app=[unknown],client=172.20.0.11 LOG:  connection received: host=172.20.0.11 port=48612
2025-08-08 02:31:59 GMT [1135]: [2-1] user=replicator,db=[unknown],app=[unknown],client=172.20.0.11 FATAL:  the database system is shutting down
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:32:00 GMT [717]: [26-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:32:00 GMT [717]: [27-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:32:00 GMT [717]: [28-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:32:00 GMT [717]: [29-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:32:00 GMT [717]: [30-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:32:01 GMT [717]: [31-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:32:01 GMT [717]: [32-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
cp: cannot create regular file '/var/lib/postgresql/archive/00000003.history': No such file or directory
2025-08-08 02:32:02 GMT [717]: [33-1] user=,db=,app=,client= LOG:  archive command failed with exit code 1
2025-08-08 02:32:02 GMT [717]: [34-1] user=,db=,app=,client= DETAIL:  The failed archive command was: test ! -f /var/lib/postgresql/archive/00000003.history && cp pg_wal/00000003.history /var/lib/postgresql/archive/00000003.history
2025-08-08 02:32:02 GMT [717]: [35-1] user=,db=,app=,client= WARNING:  archiving write-ahead log file "00000003.history" failed too many times, will try again later
2025-08-08 02:32:02 GMT [9]: [12-1] user=,db=,app=,client= LOG:  database system is shut down
